/* ============================================================
   OFFLINE FALLBACK QUESTION BANK
   Used only when the live trivia API (api.js -> OpenTDB) can't be
   reached — keeps the game playable offline or if the API is down.
   Each question: { q, options[4], answer (index), difficulty, explain,
                    optionNotes[4] — a short note per option, shown after
                    the player answers, for learning/recollection }
   Organized by category key -> array of questions
   ============================================================ */

const QUESTION_BANK = {
  science: {
    label: "Science & Nature",
    icon: "atom",
    questions: [
      { q: "What gas do plants absorb from the atmosphere for photosynthesis?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], answer: 1, difficulty: "easy", explain: "Plants pull in CO₂ and, using sunlight, convert it into glucose and oxygen.", optionNotes: ["This is what plants release, not absorb.", "Correct — the raw material for photosynthesis.", "Vital for growth, but not used here.", "Not absorbed as a gas for this process."] },
      { q: "What is the hardest natural substance on Earth?", options: ["Quartz", "Titanium", "Diamond", "Obsidian"], answer: 2, difficulty: "easy", explain: "Diamond's tightly bonded carbon lattice makes it the hardest known natural material.", optionNotes: ["Hard, but far softer than diamond.", "A strong metal, not the hardest material.", "Correct — its carbon lattice is unmatched.", "Volcanic glass — brittle, not exceptionally hard."] },
      { q: "How many bones are in the adult human body?", options: ["186", "206", "226", "246"], answer: 1, difficulty: "medium", explain: "Adults have 206 bones — babies are born with about 270 that fuse over time.", optionNotes: ["Too low — adults have more than this.", "Correct — down from about 270 at birth.", "Too high for an adult skeleton.", "Too high — closer to an infant's count."] },
      { q: "What planet has the most moons confirmed as of 2024?", options: ["Jupiter", "Neptune", "Saturn", "Uranus"], answer: 2, difficulty: "medium", explain: "Saturn overtook Jupiter after a batch of newly confirmed moons pushed its count past 140.", optionNotes: ["Long-time leader, but recently overtaken.", "Has far fewer confirmed moons.", "Correct — new discoveries pushed it past 140.", "Has a much smaller moon count."] },
      { q: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"], answer: 2, difficulty: "easy", explain: "Mitochondria convert nutrients into ATP, the cell's usable energy currency.", optionNotes: ["Holds DNA, not the energy producer.", "Builds proteins, not energy.", "Correct — converts nutrients into usable energy.", "Packages and ships proteins, not energy."] },
      { q: "Which element has the chemical symbol 'Au'?", options: ["Silver", "Aluminum", "Gold", "Argon"], answer: 2, difficulty: "easy", explain: "Au comes from the Latin word for gold, 'aurum'.", optionNotes: ["Silver's symbol is Ag, not Au.", "Aluminum's symbol is Al.", "Correct — from the Latin 'aurum.'", "Argon's symbol is Ar, a noble gas."] },
      { q: "What type of animal is a Komodo dragon?", options: ["Snake", "Lizard", "Crocodile", "Amphibian"], answer: 1, difficulty: "easy", explain: "It's the largest living species of lizard, native to Indonesia.", optionNotes: ["Komodo dragons have legs — not a snake.", "Correct — the largest living lizard species.", "A different reptile family entirely.", "It's a reptile, not an amphibian."] },
      { q: "At sea level, water boils at what temperature in Celsius?", options: ["90°C", "95°C", "100°C", "105°C"], answer: 2, difficulty: "easy", explain: "100°C is the standard boiling point of water at 1 atmosphere of pressure.", optionNotes: ["Too low for standard sea-level boiling.", "Close, but not quite the standard point.", "Correct — the standard boiling point at 1 atm.", "Too high for sea-level boiling."] },
      { q: "What force keeps planets in orbit around the sun?", options: ["Magnetism", "Gravity", "Friction", "Inertia"], answer: 1, difficulty: "easy", explain: "Gravity continuously pulls planets toward the sun, curving their path into an orbit.", optionNotes: ["Doesn't act between planets and the sun.", "Correct — it curves their path into orbit.", "Space has essentially no friction.", "Explains straight-line motion, not the pull itself."] },
      { q: "Which blood type is known as the universal donor?", options: ["A", "B", "AB", "O negative"], answer: 3, difficulty: "medium", explain: "O negative lacks A, B, and Rh antigens, so it's compatible with nearly all recipients.", optionNotes: ["Carries the A antigen, limiting compatibility.", "Carries the B antigen, limiting compatibility.", "Actually the universal recipient, not donor.", "Correct — lacks A, B, and Rh antigens."] },
      { q: "What is the study of fungi called?", options: ["Mycology", "Botany", "Entomology", "Herpetology"], answer: 0, difficulty: "hard", explain: "Mycology is the branch of biology dedicated to fungi.", optionNotes: ["Correct — the dedicated study of fungi.", "That's the study of plants.", "That's the study of insects.", "That's the study of reptiles and amphibians."] },
      { q: "Which particle has a negative electric charge?", options: ["Proton", "Neutron", "Electron", "Photon"], answer: 2, difficulty: "easy", explain: "Electrons orbit the nucleus and carry a negative charge, balancing the protons' positive charge.", optionNotes: ["Carries a positive charge.", "Carries no charge at all.", "Correct — orbits the nucleus with negative charge.", "A particle of light, not charge."] },
      { q: "What is the speed of light in a vacuum, approximately?", options: ["300,000 km/s", "150,000 km/s", "3,000 km/s", "30,000 km/s"], answer: 0, difficulty: "medium", explain: "Light travels at roughly 299,792 kilometers per second in a vacuum.", optionNotes: ["Correct — about 299,792 km/s in a vacuum.", "Half the real value.", "Far too slow — off by orders of magnitude.", "Still far too slow."] },
      { q: "Which gas makes up the largest percentage of Earth's atmosphere?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], answer: 2, difficulty: "medium", explain: "Nitrogen makes up about 78% of the atmosphere, with oxygen at roughly 21%.", optionNotes: ["Around 21% — the second most abundant.", "A tiny trace gas, not the largest share.", "Correct — about 78% of the atmosphere.", "Under 1% — a minor component."] },
      { q: "What organ produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Spleen"], answer: 1, difficulty: "medium", explain: "The pancreas releases insulin to help regulate blood sugar levels.", optionNotes: ["Processes nutrients, but doesn't make insulin.", "Correct — releases insulin to regulate blood sugar.", "Filters blood, not an insulin source.", "Filters blood cells, unrelated to insulin."] },
    ]
  },
  history: {
    label: "History",
    icon: "scroll",
    questions: [
      { q: "In what year did World War II end?", options: ["1943", "1944", "1945", "1946"], answer: 2, difficulty: "easy", explain: "The war ended in 1945 with Germany's surrender in May and Japan's in September.", optionNotes: ["Too early — the war was still ongoing.", "Close, but fighting continued into the next year.", "Correct — Germany surrendered in May, Japan in September.", "The war had already ended by this year."] },
      { q: "Who was the first President of the United States?", options: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"], answer: 2, difficulty: "easy", explain: "George Washington served as the first U.S. President from 1789 to 1797.", optionNotes: ["The third U.S. President, not the first.", "The second U.S. President.", "Correct — served from 1789 to 1797.", "A founding father, but never president."] },
      { q: "The ancient city of Rome was built on how many hills?", options: ["Five", "Six", "Seven", "Eight"], answer: 2, difficulty: "medium", explain: "Rome is famously described as being founded on seven hills.", optionNotes: ["Rome's founding legend cites more hills.", "Still one short of the traditional count.", "Correct — the famous seven hills of Rome.", "One too many for the traditional count."] },
      { q: "Which empire built Machu Picchu?", options: ["Aztec", "Maya", "Inca", "Olmec"], answer: 2, difficulty: "medium", explain: "Machu Picchu was built by the Inca Empire in the 15th century in modern-day Peru.", optionNotes: ["Centered in Mexico, not Peru.", "Based further north in Mesoamerica.", "Correct — built in the 15th century in Peru.", "An earlier civilization, unrelated to Machu Picchu."] },
      { q: "The Berlin Wall fell in which year?", options: ["1987", "1989", "1991", "1993"], answer: 1, difficulty: "medium", explain: "The wall fell in November 1989, a pivotal moment in the end of the Cold War.", optionNotes: ["Two years too early.", "Correct — fell in November 1989.", "That's closer to the USSR's dissolution.", "Several years after it actually fell."] },
      { q: "Who was the queen of ancient Egypt famously allied with Julius Caesar and Mark Antony?", options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Ankhesenamun"], answer: 1, difficulty: "easy", explain: "Cleopatra VII was the last active ruler of the Ptolemaic Kingdom of Egypt.", optionNotes: ["An earlier Egyptian queen, unrelated to Rome.", "Correct — allied with both Caesar and Antony.", "Ruled centuries before Cleopatra.", "Tutankhamun's wife, from an earlier era."] },
      { q: "Which country gifted the Statue of Liberty to the United States?", options: ["Spain", "Italy", "France", "United Kingdom"], answer: 2, difficulty: "easy", explain: "France gave the statue to the U.S. in 1886 to mark their alliance and shared ideals.", optionNotes: ["Not connected to the statue's origin.", "Not the country behind the gift.", "Correct — gifted in 1886 to mark shared ideals.", "Not the gifting nation."] },
      { q: "The Magna Carta was signed in which century?", options: ["11th", "12th", "13th", "14th"], answer: 2, difficulty: "hard", explain: "It was signed in 1215, placing it in the 13th century.", optionNotes: ["Two centuries too early.", "Still a century too early.", "Correct — signed in 1215.", "A century too late."] },
      { q: "Which war was fought between the North and South regions of the United States?", options: ["Revolutionary War", "Civil War", "War of 1812", "Spanish-American War"], answer: 1, difficulty: "easy", explain: "The American Civil War (1861–1865) was fought between the Union and the Confederacy.", optionNotes: ["That was against Britain, not North vs South.", "Correct — fought 1861–1865.", "Fought against Britain, not internally.", "Fought against Spain, not internally."] },
      { q: "The Great Wall of China was primarily built to defend against whom?", options: ["Mongol and nomadic invasions", "Japanese forces", "Russian expansion", "British colonizers"], answer: 0, difficulty: "medium", explain: "It was built and expanded over centuries chiefly to guard against northern nomadic invasions.", optionNotes: ["Correct — its main historical purpose.", "Not the wall's original purpose.", "Not a historical driver for the wall.", "Built long before British contact with China."] },
      { q: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?", options: ["Joseph Stalin", "Nikita Khrushchev", "Leonid Brezhnev", "Mikhail Gorbachev"], answer: 1, difficulty: "hard", explain: "Khrushchev led the USSR during the tense 1962 standoff with the U.S.", optionNotes: ["Died in 1953, before this crisis.", "Correct — led the USSR through the 1962 standoff.", "Took power after Khrushchev, in 1964.", "Led the USSR decades later, in the 1980s."] },
      { q: "The Renaissance began in which country?", options: ["France", "Germany", "Italy", "Spain"], answer: 2, difficulty: "medium", explain: "The Renaissance began in Italy in the 14th century before spreading across Europe.", optionNotes: ["Adopted the movement after it began elsewhere.", "Also came later than the origin.", "Correct — began there in the 14th century.", "Influenced later, not the point of origin."] },
      { q: "Which ship famously sank after hitting an iceberg in 1912?", options: ["Lusitania", "Titanic", "Britannic", "Olympic"], answer: 1, difficulty: "easy", explain: "The RMS Titanic sank on its maiden voyage on April 15, 1912.", optionNotes: ["Sunk by a torpedo in 1915, a different ship.", "Correct — sank in 1912 after hitting an iceberg.", "Titanic's sister ship, sunk later in WWI.", "Titanic's other sister ship, which had a long career."] },
      { q: "Who was the first man to walk on the Moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "John Glenn"], answer: 2, difficulty: "easy", explain: "Neil Armstrong stepped onto the lunar surface on July 20, 1969.", optionNotes: ["Walked on the Moon shortly after, not first.", "First in space, but never walked on the Moon.", "Correct — stepped out on July 20, 1969.", "First American to orbit Earth, not the Moon."] },
      { q: "The Rosetta Stone helped scholars decipher which ancient script?", options: ["Cuneiform", "Egyptian hieroglyphs", "Linear B", "Sanskrit"], answer: 1, difficulty: "hard", explain: "It provided the same text in Greek and Egyptian scripts, unlocking hieroglyphic translation.", optionNotes: ["A different ancient script, unrelated to the stone.", "Correct — unlocked through matching Greek text.", "Deciphered separately, unrelated to this stone.", "Not connected to this discovery."] },
    ]
  },
  geography: {
    label: "Geography",
    icon: "globe",
    questions: [
      { q: "What is the largest country in the world by land area?", options: ["Canada", "China", "Russia", "United States"], answer: 2, difficulty: "easy", explain: "Russia spans over 17 million square kilometers across Europe and Asia.", optionNotes: ["Second largest, but smaller than Russia.", "Large, but well behind Russia's total area.", "Correct — over 17 million square kilometers.", "Smaller in total land area than Russia."] },
      { q: "Which river is the longest in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: 1, difficulty: "medium", explain: "The Nile is generally regarded as the longest river, stretching over 6,600 km.", optionNotes: ["Carries the most water, but slightly shorter.", "Correct — over 6,600 km long.", "Asia's longest river, but shorter than the Nile.", "A major river, but far shorter."] },
      { q: "Mount Everest is located on the border of which two countries?", options: ["India and China", "Nepal and China", "Nepal and India", "Bhutan and China"], answer: 1, difficulty: "medium", explain: "Everest sits on the border between Nepal and the Tibet Autonomous Region of China.", optionNotes: ["India doesn't border Everest directly.", "Correct — sits on this exact border.", "India isn't the neighboring country here.", "Bhutan doesn't border Everest."] },
      { q: "What is the smallest country in the world by area?", options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], answer: 2, difficulty: "medium", explain: "Vatican City covers just about 0.49 square kilometers.", optionNotes: ["Small, but larger than the Vatican.", "Small, but still bigger than the Vatican.", "Correct — about 0.49 square kilometers.", "Much larger than the world's smallest country."] },
      { q: "Which desert is the largest hot desert in the world?", options: ["Gobi", "Kalahari", "Sahara", "Arabian"], answer: 2, difficulty: "easy", explain: "The Sahara spans much of North Africa, covering about 9.2 million square kilometers.", optionNotes: ["A cold desert, and smaller besides.", "Smaller than the Sahara.", "Correct — about 9.2 million square kilometers.", "Large, but still smaller than the Sahara."] },
      { q: "The Great Barrier Reef is located off the coast of which country?", options: ["Indonesia", "Australia", "Philippines", "Thailand"], answer: 1, difficulty: "easy", explain: "It stretches over 2,300 km along the coast of Queensland, Australia.", optionNotes: ["Has its own reefs, not this one.", "Correct — off the coast of Queensland.", "Known for other reef systems.", "Not the location of this reef."] },
      { q: "Which continent has the most countries?", options: ["Asia", "Europe", "Africa", "South America"], answer: 2, difficulty: "medium", explain: "Africa has 54 recognized countries, more than any other continent.", optionNotes: ["More countries than Europe, but fewer than Africa.", "Fewer countries than Africa.", "Correct — 54 recognized countries.", "Far fewer countries than Africa."] },
      { q: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2, difficulty: "medium", explain: "Canberra, not Sydney, was purpose-built to be the nation's capital.", optionNotes: ["The largest city, but not the capital.", "A major city, but not the capital.", "Correct — purpose-built as the capital.", "A state capital, not the national one."] },
      { q: "Which country has the most time zones?", options: ["Russia", "United States", "France", "China"], answer: 2, difficulty: "hard", explain: "Thanks to its overseas territories, France spans 12 time zones.", optionNotes: ["Has many zones, but fewer than France's total.", "Fewer zones once territories are counted for France.", "Correct — 12 zones thanks to overseas territories.", "Uses a single official time zone nationwide."] },
      { q: "The Panama Canal connects which two oceans?", options: ["Indian and Pacific", "Atlantic and Pacific", "Atlantic and Indian", "Arctic and Pacific"], answer: 1, difficulty: "easy", explain: "It links the Atlantic and Pacific Oceans, cutting across the Isthmus of Panama.", optionNotes: ["Wrong ocean pairing for this canal.", "Correct — cuts across the Isthmus of Panama.", "Not the oceans this canal connects.", "Not connected to the Panama Canal."] },
      { q: "Which African country was formerly known as Abyssinia?", options: ["Kenya", "Ethiopia", "Sudan", "Somalia"], answer: 1, difficulty: "hard", explain: "Ethiopia was historically referred to as Abyssinia by Europeans.", optionNotes: ["A neighboring country, not the historical name.", "Correct — the old European name for the region.", "A different neighboring country.", "Not the country historically called Abyssinia."] },
      { q: "What is the driest place on Earth?", options: ["Sahara Desert", "Atacama Desert", "Gobi Desert", "Mojave Desert"], answer: 1, difficulty: "hard", explain: "Parts of Chile's Atacama Desert have gone decades without measurable rainfall.", optionNotes: ["Very dry, but not the driest.", "Correct — parts go decades without rain.", "Dry, but wetter than the Atacama.", "Receives more rainfall than the Atacama."] },
      { q: "Which sea is the saltiest body of water in the world?", options: ["Red Sea", "Caspian Sea", "Dead Sea", "Black Sea"], answer: 2, difficulty: "medium", explain: "The Dead Sea's extreme salinity, roughly 34%, is what makes bodies float easily.", optionNotes: ["Salty, but not the saltiest.", "Actually the world's largest lake, less salty.", "Correct — roughly 34% salinity.", "Far less salty than the Dead Sea."] },
      { q: "Which two countries share the longest international land border?", options: ["USA and Canada", "Russia and China", "Chile and Argentina", "India and China"], answer: 0, difficulty: "hard", explain: "The U.S.–Canada border stretches over 8,800 km, the longest in the world.", optionNotes: ["Correct — over 8,800 km long.", "Long, but shorter than the US–Canada border.", "Long, but still shorter than US–Canada.", "Much shorter than the US–Canada border."] },
      { q: "What is the capital city of Japan?", options: ["Osaka", "Kyoto", "Tokyo", "Yokohama"], answer: 2, difficulty: "easy", explain: "Tokyo has been Japan's capital since 1868.", optionNotes: ["A major city, but not the capital.", "The former imperial capital, not the current one.", "Correct — capital since 1868.", "A large port city, not the capital."] },
    ]
  },
  movies: {
    label: "Movies",
    icon: "film",
    questions: [
      { q: "Which movie won the Academy Award for Best Picture in 1994?", options: ["Pulp Fiction", "Forrest Gump", "The Shawshank Redemption", "The Lion King"], answer: 1, difficulty: "medium", explain: "Forrest Gump took home Best Picture at the 67th Academy Awards.", optionNotes: ["Nominated, but didn't win Best Picture.", "Correct — won at the 67th Academy Awards.", "A beloved nominee, but lost that year.", "Wasn't nominated for Best Picture."] },
      { q: "Who directed the movie 'Jaws'?", options: ["George Lucas", "Steven Spielberg", "Martin Scorsese", "Francis Ford Coppola"], answer: 1, difficulty: "easy", explain: "Steven Spielberg directed Jaws in 1975, often called the first summer blockbuster.", optionNotes: ["Directed Star Wars, not Jaws.", "Correct — directed Jaws in 1975.", "Known for different films entirely.", "Directed The Godfather, not Jaws."] },
      { q: "Who played the Joker in 'The Dark Knight' (2008)?", options: ["Jared Leto", "Joaquin Phoenix", "Heath Ledger", "Jack Nicholson"], answer: 2, difficulty: "easy", explain: "Heath Ledger's performance earned a posthumous Academy Award.", optionNotes: ["Played Joker in a later, different film.", "Played Joker in a separate 2019 film.", "Correct — won a posthumous Oscar for the role.", "Played Joker in the 1989 Batman film."] },
      { q: "What is the highest-grossing film of all time (unadjusted for inflation)?", options: ["Titanic", "Avengers: Endgame", "Avatar", "Star Wars: The Force Awakens"], answer: 2, difficulty: "medium", explain: "Avatar (2009), boosted by re-releases, holds the top spot at the global box office.", optionNotes: ["A former record holder, since surpassed.", "Close, but ultimately behind Avatar's total.", "Correct — helped by several re-releases.", "High-grossing, but below Avatar's total."] },
      { q: "Which actress played Katniss Everdeen in 'The Hunger Games'?", options: ["Emma Watson", "Kristen Stewart", "Jennifer Lawrence", "Shailene Woodley"], answer: 2, difficulty: "easy", explain: "Jennifer Lawrence portrayed Katniss across the four-film franchise.", optionNotes: ["Known for the Harry Potter films instead.", "Known for the Twilight films instead.", "Correct — played Katniss across the franchise.", "Starred in Divergent, a different franchise."] },
      { q: "What was the first feature-length fully computer-animated film?", options: ["Shrek", "Toy Story", "A Bug's Life", "Antz"], answer: 1, difficulty: "medium", explain: "Pixar's Toy Story (1995) was the first entirely CGI feature film.", optionNotes: ["Came several years after the first CGI feature.", "Correct — released by Pixar in 1995.", "Pixar's second feature, not the first.", "Released around the same time, but not first."] },
      { q: "Who directed 'Inception' and 'Interstellar'?", options: ["Ridley Scott", "Denis Villeneuve", "Christopher Nolan", "David Fincher"], answer: 2, difficulty: "medium", explain: "Christopher Nolan directed both critically acclaimed sci-fi epics.", optionNotes: ["Directed Blade Runner, not these films.", "Directed Dune, a different director.", "Correct — directed both films.", "Known for Fight Club and other films."] },
      { q: "Who directed 'Titanic' (1997)?", options: ["James Cameron", "Steven Spielberg", "Ridley Scott", "Peter Jackson"], answer: 0, difficulty: "easy", explain: "James Cameron wrote and directed Titanic, which won 11 Academy Awards.", optionNotes: ["Correct — also directed Avatar.", "Directed many classics, but not Titanic.", "Known for different epics.", "Directed The Lord of the Rings instead."] },
      { q: "In what year was the first 'Star Wars' film released?", options: ["1975", "1977", "1979", "1981"], answer: 1, difficulty: "medium", explain: "Star Wars (later subtitled A New Hope) premiered in 1977.", optionNotes: ["Two years too early.", "Correct — premiered as A New Hope.", "Two years too late.", "Several years after the actual release."] },
      { q: "Who plays Iron Man in the Marvel Cinematic Universe films?", options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], answer: 1, difficulty: "easy", explain: "Robert Downey Jr. launched the MCU as Tony Stark in Iron Man (2008).", optionNotes: ["Played Captain America instead.", "Correct — launched the MCU as Tony Stark.", "Played Thor instead.", "Played Bruce Banner / Hulk instead."] },
      { q: "Which 2019 film became the first non-English-language movie to win the Best Picture Oscar?", options: ["Roma", "Parasite", "Amélie", "Crouching Tiger, Hidden Dragon"], answer: 1, difficulty: "hard", explain: "Bong Joon-ho's Parasite (South Korea) made history at the 2020 ceremony.", optionNotes: ["Nominated the year prior, didn't win Best Picture.", "Correct — made history at the 2020 ceremony.", "A beloved French film, but never won this award.", "Won Best Foreign Film, not Best Picture."] },
      { q: "Which Disney film features the song 'Circle of Life'?", options: ["Aladdin", "The Lion King", "Pocahontas", "Tarzan"], answer: 1, difficulty: "easy", explain: "'Circle of Life' opens The Lion King (1994).", optionNotes: ["Features different songs entirely.", "Correct — opens the film.", "A different Disney soundtrack.", "Features a different song set."] },
    ]
  },
  music: {
    label: "Music",
    icon: "music",
    questions: [
      { q: "Which band released the album 'Abbey Road'?", options: ["The Rolling Stones", "The Beatles", "Pink Floyd", "The Who"], answer: 1, difficulty: "easy", explain: "The Beatles released Abbey Road in 1969, their last recorded album.", optionNotes: ["A contemporary band, but not this album's artist.", "Correct — released in 1969.", "Known for different iconic albums.", "A different classic rock band."] },
      { q: "Which artist is known as the 'King of Pop'?", options: ["Prince", "Elvis Presley", "Michael Jackson", "Stevie Wonder"], answer: 2, difficulty: "easy", explain: "Michael Jackson earned the nickname through his massive influence on pop music.", optionNotes: ["Had his own legendary status, different nickname.", "Known as the King of Rock and Roll.", "Correct — earned this famous nickname.", "A music legend, but not this nickname."] },
      { q: "Who composed the score for 'Star Wars'?", options: ["Hans Zimmer", "John Williams", "James Horner", "Danny Elfman"], answer: 1, difficulty: "medium", explain: "John Williams composed the iconic Star Wars score, starting in 1977.", optionNotes: ["Scored many other blockbusters instead.", "Correct — composing since the 1977 original.", "Scored Titanic and Avatar instead.", "Known for Batman and other scores."] },
      { q: "Which musical is based on the life of American founding father Alexander Hamilton?", options: ["Wicked", "Hamilton", "Dear Evan Hansen", "The Book of Mormon"], answer: 1, difficulty: "easy", explain: "Lin-Manuel Miranda created Hamilton, blending hip-hop with historical drama.", optionNotes: ["Tells the Wizard of Oz backstory instead.", "Correct — created by Lin-Manuel Miranda.", "A different original musical.", "A comedic musical, unrelated to Hamilton."] },
      { q: "Which pop star's albums include '1989' and 'Fearless'?", options: ["Ariana Grande", "Taylor Swift", "Katy Perry", "Selena Gomez"], answer: 1, difficulty: "easy", explain: "Both albums are by Taylor Swift, with 1989 marking her pivot to pop.", optionNotes: ["Has her own separate discography.", "Correct — both albums are hers.", "Known for different album titles.", "A different pop artist's catalog."] },
      { q: "What instrument is Yo-Yo Ma famous for playing?", options: ["Violin", "Piano", "Cello", "Flute"], answer: 2, difficulty: "medium", explain: "Yo-Yo Ma is a world-renowned cellist.", optionNotes: ["A related string instrument, not his.", "Not the instrument he's known for.", "Correct — a world-renowned cellist.", "Not a string instrument like his."] },
      { q: "Which British rock band released the album 'The Dark Side of the Moon'?", options: ["Led Zeppelin", "Pink Floyd", "Queen", "The Who"], answer: 1, difficulty: "medium", explain: "Pink Floyd's 1973 album became one of the best-selling albums in history.", optionNotes: ["Known for different landmark albums.", "Correct — released the album in 1973.", "A different iconic rock band.", "Known for other classic rock records."] },
      { q: "Beyoncé rose to fame as a member of which girl group?", options: ["TLC", "Destiny's Child", "En Vogue", "Spice Girls"], answer: 1, difficulty: "easy", explain: "Beyoncé was the lead singer of Destiny's Child before going solo in 2003.", optionNotes: ["A contemporary group, but not hers.", "Correct — she was the lead singer.", "A different R&B group.", "A British group, unrelated to Beyoncé."] },
      { q: "What is the best-selling album of all time?", options: ["Back in Black", "Thriller", "The Bodyguard", "Rumours"], answer: 1, difficulty: "medium", explain: "Michael Jackson's Thriller (1982) remains the best-selling album ever.", optionNotes: ["A huge seller, but ranks below Thriller.", "Correct — Michael Jackson's 1982 album.", "A top-selling soundtrack, but not the highest.", "A classic album, but sold less than Thriller."] },
      { q: "Which Baroque composer wrote 'The Four Seasons'?", options: ["Johann Sebastian Bach", "Antonio Vivaldi", "George Frideric Handel", "Wolfgang Amadeus Mozart"], answer: 1, difficulty: "hard", explain: "Antonio Vivaldi composed The Four Seasons around 1723.", optionNotes: ["A contemporary composer, different work.", "Correct — composed it around 1723.", "Known for other Baroque works.", "Born after this piece was written."] },
      { q: "Elvis Presley is commonly known as the King of what genre?", options: ["Jazz", "Rock and Roll", "Country", "Blues"], answer: 1, difficulty: "easy", explain: "Elvis Presley earned the title 'King of Rock and Roll' in the 1950s.", optionNotes: ["Not the genre tied to this nickname.", "Correct — earned in the 1950s.", "Influenced by it, but not this title.", "A major influence on him, not the title."] },
      { q: "Which music streaming service was founded in Sweden?", options: ["Spotify", "Deezer", "Tidal", "Pandora"], answer: 0, difficulty: "medium", explain: "Spotify launched in Stockholm in 2008.", optionNotes: ["Correct — launched in Stockholm in 2008.", "Founded in France instead.", "Founded in Norway, later based in the US.", "Founded in the United States."] },
    ]
  },
  videogames: {
    label: "Video Games",
    icon: "gamepad",
    questions: [
      { q: "Which company created the Mario franchise?", options: ["Sega", "Sony", "Nintendo", "Capcom"], answer: 2, difficulty: "easy", explain: "Nintendo introduced Mario in 1981's Donkey Kong before giving him his own series.", optionNotes: ["Known for Sonic, a rival franchise.", "Makes consoles, not this character.", "Correct — introduced Mario in 1981.", "Known for different franchises like Street Fighter."] },
      { q: "In what year was the first PlayStation console released?", options: ["1992", "1994", "1996", "1998"], answer: 1, difficulty: "medium", explain: "Sony released the original PlayStation in Japan in December 1994.", optionNotes: ["Two years too early.", "Correct — released in Japan that December.", "Two years too late.", "Several years after the actual release."] },
      { q: "Which sandbox game, created by Markus Persson, involves mining and building with blocks?", options: ["Terraria", "Minecraft", "Roblox", "Fortnite"], answer: 1, difficulty: "easy", explain: "Minecraft was created by Markus 'Notch' Persson and released in 2011.", optionNotes: ["A similar but separate game.", "Correct — created by Markus 'Notch' Persson.", "A different platform, different creators.", "Made by Epic Games, unrelated to Persson."] },
      { q: "Which video game franchise features a super-soldier called Master Chief?", options: ["Gears of War", "Halo", "Destiny", "Call of Duty"], answer: 1, difficulty: "medium", explain: "Master Chief has been the protagonist of the Halo series since 2001.", optionNotes: ["Features a different protagonist.", "Correct — his home series since 2001.", "A different sci-fi shooter series.", "Features different characters entirely."] },
      { q: "In gaming, what does 'NPC' stand for?", options: ["New Player Character", "Non-Player Character", "Networked Player Console", "Non-Playable Console"], answer: 1, difficulty: "easy", explain: "NPCs are characters controlled by the game rather than a human player.", optionNotes: ["Close wording, but not the real term.", "Correct — controlled by the game itself.", "Not a real gaming term.", "Confuses hardware with in-game characters."] },
      { q: "Which company developed 'The Legend of Zelda' franchise?", options: ["Nintendo", "Square Enix", "Capcom", "Konami"], answer: 0, difficulty: "easy", explain: "Nintendo's Zelda series debuted in 1986, created by Shigeru Miyamoto.", optionNotes: ["Correct — debuted the series in 1986.", "Known for Final Fantasy instead.", "Known for Resident Evil and other franchises.", "Known for Metal Gear and other series."] },
      { q: "In the arcade game Pac-Man, what are the ghosts trying to do?", options: ["Collect fruit", "Catch Pac-Man", "Escape the maze", "Steal pellets"], answer: 1, difficulty: "easy", explain: "The four ghosts chase Pac-Man through the maze, ending the game if they catch him.", optionNotes: ["That's Pac-Man's job, not the ghosts'.", "Correct — catching him ends the game.", "Ghosts stay within the maze.", "Pac-Man eats the pellets, not the ghosts."] },
      { q: "Games like League of Legends and Dota 2 belong to which genre?", options: ["RTS", "MOBA", "FPS", "JRPG"], answer: 1, difficulty: "medium", explain: "MOBA stands for Multiplayer Online Battle Arena.", optionNotes: ["A related but distinct strategy genre.", "Correct — Multiplayer Online Battle Arena.", "A shooter genre, not this one.", "A role-playing genre, unrelated to these games."] },
      { q: "As of the mid-2020s, what is the best-selling video game of all time?", options: ["Tetris", "Minecraft", "Grand Theft Auto V", "Wii Sports"], answer: 1, difficulty: "medium", explain: "Minecraft has sold over 300 million copies across all platforms.", optionNotes: ["A massive seller, but ranks below Minecraft.", "Correct — over 300 million copies sold.", "Hugely popular, but sold fewer copies.", "Boosted by console bundling, but sold less."] },
      { q: "In Fortnite, what is the name of the shrinking play area that forces players together?", options: ["The Storm", "The Zone", "The Blight", "The Void"], answer: 0, difficulty: "medium", explain: "The Storm damages players who linger outside the safe zone.", optionNotes: ["Correct — damages players outside the safe zone.", "Not the game's official term.", "Not a Fortnite mechanic.", "Not the name used in-game."] },
      { q: "Which Japanese company created the PlayStation console line?", options: ["Nintendo", "Sega", "Sony", "Sharp"], answer: 2, difficulty: "easy", explain: "Sony has produced the PlayStation family since 1994.", optionNotes: ["Makes consoles, but not this one.", "A console rival, not the PlayStation maker.", "Correct — has produced PlayStation since 1994.", "An electronics maker, not this console maker."] },
      { q: "Which game popularized the 'battle royale' genre starting in 2017?", options: ["Fortnite", "PUBG", "Apex Legends", "Call of Duty: Warzone"], answer: 1, difficulty: "hard", explain: "PlayerUnknown's Battlegrounds (PUBG) launched the genre's mainstream boom in 2017.", optionNotes: ["Popularized the genre further, but came after.", "Correct — launched the genre's boom in 2017.", "Released two years later, in 2019.", "Released years later, in 2020."] },
    ]
  },
  sports: {
    label: "Sports",
    icon: "trophy",
    questions: [
      { q: "How many players are on a standard soccer team on the field?", options: ["9", "10", "11", "12"], answer: 2, difficulty: "easy", explain: "Each soccer team fields 11 players, including the goalkeeper.", optionNotes: ["Two players short of a full team.", "One player short of a full team.", "Correct — including the goalkeeper.", "One too many for a legal lineup."] },
      { q: "In which sport would you perform a slam dunk?", options: ["Volleyball", "Basketball", "Tennis", "Badminton"], answer: 1, difficulty: "easy", explain: "A slam dunk is a basketball shot where the player forces the ball through the hoop.", optionNotes: ["No hoop involved in this sport.", "Correct — forcing the ball through the hoop.", "A racket sport, unrelated to dunking.", "Also a racket sport, no hoop."] },
      { q: "How often are the Summer Olympic Games held?", options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], answer: 2, difficulty: "easy", explain: "The Summer Olympics take place every four years.", optionNotes: ["Too frequent — not the real cycle.", "Not the actual Olympic cycle.", "Correct — the standard Olympic cycle.", "Longer than the real cycle."] },
      { q: "Which country has won the most FIFA World Cup titles?", options: ["Germany", "Argentina", "Brazil", "Italy"], answer: 2, difficulty: "medium", explain: "Brazil has won the World Cup five times, more than any other nation.", optionNotes: ["Multiple titles, but fewer than Brazil.", "Multiple titles, but still behind Brazil.", "Correct — five World Cup titles.", "Four titles, one behind Brazil."] },
      { q: "In tennis, what is a score of zero called?", options: ["Nil", "Love", "Duck", "Blank"], answer: 1, difficulty: "medium", explain: "'Love' is the traditional term for zero in tennis scoring.", optionNotes: ["Used in soccer, not tennis.", "Correct — the traditional tennis term.", "A cricket term for zero runs.", "Not an official tennis scoring term."] },
      { q: "What sport is known as 'America's pastime'?", options: ["American Football", "Basketball", "Baseball", "Ice Hockey"], answer: 2, difficulty: "easy", explain: "Baseball has been called America's pastime since the 19th century.", optionNotes: ["The most popular sport today, but not this nickname.", "An American invention, but not this title.", "Correct — nicknamed since the 19th century.", "More associated with Canada historically."] },
      { q: "How many rings are on the Olympic flag?", options: ["4", "5", "6", "7"], answer: 1, difficulty: "easy", explain: "The five interlocking rings represent the five inhabited continents.", optionNotes: ["One ring short of the real count.", "Correct — representing the five continents.", "One ring too many.", "Two rings too many."] },
      { q: "Which country invented the sport of cricket?", options: ["Australia", "India", "England", "South Africa"], answer: 2, difficulty: "medium", explain: "Cricket's origins trace back to 16th-century England.", optionNotes: ["Adopted the sport, didn't invent it.", "Now a cricket powerhouse, but not its origin.", "Correct — traced back to the 16th century.", "Adopted the sport later on."] },
      { q: "In golf, what term describes one stroke under par?", options: ["Bogey", "Eagle", "Birdie", "Albatross"], answer: 2, difficulty: "medium", explain: "A birdie is scoring one stroke fewer than the hole's par.", optionNotes: ["One stroke over par, the opposite direction.", "Two strokes under par, not one.", "Correct — one stroke under par.", "Three strokes under par, even rarer."] },
      { q: "Which martial art originated in Brazil and focuses on ground grappling?", options: ["Judo", "Taekwondo", "Brazilian Jiu-Jitsu", "Karate"], answer: 2, difficulty: "medium", explain: "Brazilian Jiu-Jitsu evolved from Judo, emphasizing ground control and submissions.", optionNotes: ["The martial art BJJ evolved from.", "A Korean striking art, unrelated.", "Correct — focuses on ground grappling.", "A striking art, not grappling-focused."] },
      { q: "How many players are on a standard basketball team on the court?", options: ["4", "5", "6", "7"], answer: 1, difficulty: "easy", explain: "Basketball teams field five players at a time on the court.", optionNotes: ["One player short of a full team.", "Correct — five players per side on court.", "One too many for a legal lineup.", "Two too many players on court."] },
      { q: "The Tour de France is primarily a race for which sport?", options: ["Running", "Cycling", "Motorsport", "Triathlon"], answer: 1, difficulty: "easy", explain: "The Tour de France is the world's most famous cycling stage race.", optionNotes: ["No running involved in this race.", "Correct — the world's most famous cycling race.", "No motorized vehicles in this event.", "Combines three sports; this race is cycling only."] },
      { q: "Which country hosted the 2016 Summer Olympics?", options: ["China", "United Kingdom", "Brazil", "Japan"], answer: 2, difficulty: "medium", explain: "Rio de Janeiro, Brazil hosted the 2016 Summer Games.", optionNotes: ["Hosted in 2008, not 2016.", "Hosted in 2012, not 2016.", "Correct — Rio de Janeiro hosted in 2016.", "Hosted later, in 2021 (postponed from 2020)."] },
      { q: "In American football, how many points is a touchdown worth?", options: ["3", "6", "7", "8"], answer: 1, difficulty: "easy", explain: "A touchdown is worth 6 points, with an extra point or two-point conversion possible after.", optionNotes: ["That's the value of a field goal.", "Correct — plus a possible extra point or two.", "Only reached after a successful extra point.", "Only reached with a two-point conversion added."] },
      { q: "Which swimmer holds the record for most Olympic gold medals?", options: ["Mark Spitz", "Ian Thorpe", "Michael Phelps", "Ryan Lochte"], answer: 2, difficulty: "medium", explain: "Michael Phelps has won 23 Olympic gold medals, the most of any athlete.", optionNotes: ["Held the record before Phelps surpassed it.", "A champion swimmer, but far fewer golds.", "Correct — 23 Olympic gold medals.", "A decorated swimmer, but well behind Phelps."] },
    ]
  },
  arts: {
    label: "Art & Literature",
    icon: "palette",
    questions: [
      { q: "Who painted the Mona Lisa?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], answer: 1, difficulty: "easy", explain: "Leonardo da Vinci painted the Mona Lisa in the early 16th century.", optionNotes: ["Painted the Sistine Chapel, not this work.", "Correct — painted it in the early 1500s.", "A contemporary artist, different masterpieces.", "A sculptor, not known for this painting."] },
      { q: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Christopher Marlowe"], answer: 1, difficulty: "easy", explain: "Shakespeare wrote the tragedy around 1594–96.", optionNotes: ["Wrote novels centuries later.", "Correct — written around 1594–96.", "Wrote novels, not this play.", "A contemporary playwright, different works."] },
      { q: "Which artist is known for cutting off part of his own ear?", options: ["Pablo Picasso", "Claude Monet", "Vincent van Gogh", "Salvador Dalí"], answer: 2, difficulty: "medium", explain: "Van Gogh famously severed part of his ear during a mental health crisis in 1888.", optionNotes: ["Known for Cubism, not this incident.", "An Impressionist painter, unrelated to this story.", "Correct — happened during an 1888 crisis.", "A Surrealist, not connected to this event."] },
      { q: "'1984' and 'Animal Farm' were written by which author?", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], answer: 1, difficulty: "easy", explain: "George Orwell wrote both dystopian classics.", optionNotes: ["Wrote Brave New World instead.", "Correct — wrote both dystopian classics.", "Wrote Fahrenheit 451, a different classic.", "Wrote earlier science fiction classics."] },
      { q: "The sculpture 'The Thinker' was created by which artist?", options: ["Auguste Rodin", "Michelangelo", "Antonio Canova", "Gian Lorenzo Bernini"], answer: 0, difficulty: "medium", explain: "Auguste Rodin sculpted The Thinker, originally part of a larger work called The Gates of Hell.", optionNotes: ["Correct — originally part of The Gates of Hell.", "Known for different sculptures like David.", "A Neoclassical sculptor, different works.", "A Baroque sculptor, different era."] },
      { q: "Which novel begins with the line 'Call me Ishmael'?", options: ["The Old Man and the Sea", "Moby-Dick", "Treasure Island", "The Great Gatsby"], answer: 1, difficulty: "medium", explain: "Herman Melville's Moby-Dick opens with that famous line.", optionNotes: ["A different Hemingway-style opening.", "Correct — Melville's famous opening line.", "Opens very differently.", "Opens with a different famous line."] },
      { q: "Who painted 'The Starry Night'?", options: ["Claude Monet", "Vincent van Gogh", "Georges Seurat", "Edvard Munch"], answer: 1, difficulty: "easy", explain: "Van Gogh painted The Starry Night in 1889 while at an asylum in France.", optionNotes: ["An Impressionist, different signature style.", "Correct — painted it in 1889.", "Known for pointillism, a different technique.", "Painted The Scream, a different work."] },
      { q: "Which art movement is Salvador Dalí most associated with?", options: ["Cubism", "Impressionism", "Surrealism", "Fauvism"], answer: 2, difficulty: "medium", explain: "Dalí was a leading figure of the Surrealist movement.", optionNotes: ["Associated with Picasso and Braque instead.", "An earlier, very different movement.", "Correct — Dalí was a leading figure.", "Known for bold color, a different movement."] },
      { q: "'Pride and Prejudice' was written by which author?", options: ["Emily Brontë", "Jane Austen", "Virginia Woolf", "George Eliot"], answer: 1, difficulty: "easy", explain: "Jane Austen published Pride and Prejudice in 1813.", optionNotes: ["Wrote Wuthering Heights instead.", "Correct — published it in 1813.", "Wrote in a later, modernist style.", "Wrote Middlemarch, a different novel."] },
      { q: "The ceiling of the Sistine Chapel was painted by whom?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Titian"], answer: 0, difficulty: "easy", explain: "Michelangelo painted the ceiling between 1508 and 1512.", optionNotes: ["Correct — painted it between 1508 and 1512.", "Painted the Mona Lisa instead.", "Painted frescoes nearby, not the ceiling.", "A Venetian painter, unrelated to this ceiling."] },
      { q: "Who wrote 'One Hundred Years of Solitude'?", options: ["Jorge Luis Borges", "Gabriel García Márquez", "Mario Vargas Llosa", "Pablo Neruda"], answer: 1, difficulty: "hard", explain: "Gabriel García Márquez published this landmark of magical realism in 1967.", optionNotes: ["Known for short stories, a different author.", "Correct — published it in 1967.", "A different acclaimed Latin American author.", "A celebrated poet, not this novel's author."] },
      { q: "Which museum houses the Mona Lisa?", options: ["The British Museum", "The Louvre", "The Uffizi", "The Prado"], answer: 1, difficulty: "easy", explain: "The Mona Lisa is displayed in the Louvre in Paris.", optionNotes: ["Houses different treasures, not this painting.", "Correct — displayed in Paris.", "An Italian gallery, different collection.", "A Spanish museum, different collection."] },
      { q: "Who is the author of the 'Harry Potter' series?", options: ["J.R.R. Tolkien", "J.K. Rowling", "C.S. Lewis", "Roald Dahl"], answer: 1, difficulty: "easy", explain: "J.K. Rowling wrote the seven-book Harry Potter series.", optionNotes: ["Wrote The Lord of the Rings instead.", "Correct — wrote all seven books.", "Wrote The Chronicles of Narnia instead.", "Wrote Charlie and the Chocolate Factory instead."] },
      { q: "Which composer went completely deaf later in life yet continued composing?", options: ["Mozart", "Bach", "Beethoven", "Chopin"], answer: 2, difficulty: "medium", explain: "Beethoven continued composing masterpieces, including his Ninth Symphony, after losing his hearing.", optionNotes: ["Died before experiencing significant hearing loss.", "Had vision problems late in life, not deafness.", "Correct — composed his Ninth Symphony while deaf.", "Struggled with illness, but not deafness."] },
      { q: "What art style is Pablo Picasso and Georges Braque credited with founding?", options: ["Cubism", "Dadaism", "Expressionism", "Pop Art"], answer: 0, difficulty: "medium", explain: "Picasso and Braque pioneered Cubism in the early 20th century.", optionNotes: ["Correct — pioneered by Picasso and Braque.", "An anti-art movement, different founders.", "Associated with different artists like Munch.", "A much later movement, different artists."] },
    ]
  },
};

// Flatten helper used by the quiz engine
function getAllQuestions() {
  const all = [];
  Object.entries(QUESTION_BANK).forEach(([key, cat]) => {
    cat.questions.forEach(q => all.push({ ...q, category: key, categoryLabel: cat.label }));
  });
  return all;
}

// Fallback category metadata, used only if api.js fails to load at all
// (e.g. the script tag itself was blocked). Mirrors TriviaAPI.CATEGORY_META.
const LOCAL_CATEGORY_META = {
  all: { label: "All Categories", icon: "shuffle", blurb: `${Object.values(QUESTION_BANK).reduce((n, c) => n + c.questions.length, 0)} offline questions` },
  science: { label: "Science & Nature", icon: "atom", blurb: "Biology, physics, space & more" },
  history: { label: "History", icon: "scroll", blurb: "Empires, wars & turning points" },
  geography: { label: "Geography", icon: "globe", blurb: "Places, borders & landmarks" },
  movies: { label: "Movies", icon: "film", blurb: "Directors, plots & box office" },
  music: { label: "Music", icon: "music", blurb: "Artists, albums & instruments" },
  videogames: { label: "Video Games", icon: "gamepad", blurb: "Consoles, characters & lore" },
  sports: { label: "Sports", icon: "trophy", blurb: "Teams, records & rules of play" },
  arts: { label: "Art & Literature", icon: "palette", blurb: "Painters, authors & classics" },
};
